ifeq ($(CONFIG_PROJECT_PINE), y)
    obj-y += stub/ audio-pine/
    header-y += stub/include/uapi/ audio-pine/include/uapi/
else
    obj-y += stub/ audio/
    header-y += stub/include/uapi/ audio/include/uapi/
endif